### ISSUE TITLE
Global socket options arguements not parsed correctly

### ISSUE THREAD

**Issue by raspberrypython** [dperson/samba#76]
When trying to add alternative socket options to improve performance:
`socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=65536 SO_SNDBUF=65536`
the smb.conf file ends up with the following:
`socket options = 65536`

**Comment by dperson** [comment]
Okay, It should be fixed now. Thanks for the report.

I can't test at the moment, so let me know if it's still misbehaving.

**Comment by pabloromeo** [comment]
This issue is still occurring:
`socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072`

And the resulting section in smb.conf ends up as:
```
[global]
   socket options = 131072
```

**Comment by dperson** [comment]
Doh! I guess I never got back to test it. I think it's really fixed now. Thanks for letting me know.
